### ISSUE TITLE
Importing a module no longer works

### ISSUE THREAD

**Issue by andy31lewis** [brython-dev/brython#1118]
Importing a module worked correctly in 3.7.1 but in 3.7.2 the import fails with "ImportError: No module named xxxxxxx".
This is the case no matter whether the module is a file module.py, or a folder containing an `__init__.py` file, or an import from within a folder `import folder.module as mymodule`.

Having done some digging,  I find that the change seems to have been introduced in commit 4894051 Fixes #1093 : wrong assignment in "for x in empty range", on April 17th, although I can't see what that title has to do with importing a module :-)

Thank you as always
Andy

**Comment by PierreQuentel** [comment]
Many thanks for reporting this very soon after the release of version 3.7.2... It's the kind of bug that doesn't show in the development environment, but crashes everything in an environment created by `python -m brython --install`. I have published release 3.7.3 with a bug fix.

By the way, the bug was indeed introduced by the previous commit, 6c8b2fa8adc5f02e1e3ea60eafb34472685b0e0a, with a name more related to the issue :  _Limit the number of tries when importing from a module in the standard library_

**Comment by darthglowball** [comment]
I can't import anything. I try to import regex module from a Brython script in my Client folder. regex is located at `...\Client\resources\backend\javascript_packages\Brython\Lib\site-packages\regex`. I do:

`import regex` and I get this error:

```
Error 0 means that Python module regex was not found at url file:///C:/Users/hp/Documents/Programming/Web%20development/File%20content%20searcher%20and%20categorizer/Client/regex.py
brython.js:8724 Failed to load resource: net::ERR_FILE_NOT_FOUND
brython.js:8729 Error 0 means that Python module regex was not found at url file:///C:/Users/hp/Documents/Programming/Web%20development/File%20content%20searcher%20and%20categorizer/Client/regex/__init__.py
brython.js:8724 Failed to load resource: net::ERR_FILE_NOT_FOUND
brython.js:8729 Error 0 means that Python module regex was not found at url file:///C:/Users/hp/Documents/Programming/Web%20development/File%20content%…t/resources/backend/javascript_packages/Brython/Lib/site-packages/regex.py
brython.js:8724 Failed to load resource: net::ERR_FILE_NOT_FOUND
brython.js:8729 Error 0 means that Python module regex was not found at url file:///C:/Users/hp/Documents/Programming/Web%20development/File%20content%…es/backend/javascript_packages/Brython/Lib/site-packages/regex/__init__.py
brython.js:5979 Traceback (most recent call last):
ImportError: No module named regex
brython.js:5124 Uncaught Error
    at Object._b_.ImportError.$factory (eval at $make_exc (brython.js:7501), <anonymous>:71:321)
    at Object.import_hooks (brython.js:13227)
    at $B.$__import__ (brython.js:9028)
    at Object.$B.$import (brython.js:9061)
    at eval (eval at $B.loop (brython.js:5108), <anonymous>:20:8)
    at $B.loop (brython.js:5108)
    at $B.inImported (brython.js:5098)
    at $B.loop (brython.js:5114)
    at IDBOpenDBRequest.idb_cx.onsuccess (brython.js:5078)
```
I'm using CEF. The __init__.py is present in regex folder. If you look at the part `regex was not found at url file:///C:/Users/hp/Documents/Programming/Web%20development/File%20content%…es/backend/javascript_packages/Brython/Lib/site-packages/regex/__init__.py` it looks like resources folder isn't present, but there's `...es` which I think is an abbreviation for that folder. So the error shows the right paths to check, but the module isn't found. I'm 100% sure that the modules are in the correct folders with the correct names.
