### ISSUE TITLE
sys.stderr has no flush() method

### ISSUE THREAD

**Issue by schmave** [brython-dev/brython#1106]
This code runs fine if you are using the Brython HTML editor, but not if it is run outside of that environment:

```python
import sys
sys.stderr.flush()
```

Here's the error message:

```
Traceback (most recent call last):
  module __main__ line 3
    sys.stderr.flush()
AttributeError: 'io' object has no attribute 'flush'
```

I think that this bug was introduced by commit 42e7c95079dffbe7471cf59d76ac4823fcc11e4b

**Comment by schmave** [comment]
Thanks for all the fixes, @PierreQuentel !
