### ISSUE TITLE
@dataclass pickling error in 3.9.6

### ISSUE THREAD

**Issue by alex-and-or** [brython-dev/brython#1782]
### Issue

Pickling a dataclass worked in 3.9.5 but now gives the following console trace in 3.9.6:

```
brython.min.js:81 Javascript exception: TypeError: t.$jsobj.hasOwnProperty is not a function
    at Object.m.$getitem (brython.min.js:92)
    at m.get (brython.min.js:92)
    at _is_type3808 (eval at VFSLoader.exec_module (brython.min.js:91), <anonymous>:2600:209)
    at _get_field3809 (eval at VFSLoader.exec_module (brython.min.js:91), <anonymous>:2709:369)
    at eval (eval at VFSLoader.exec_module (brython.min.js:91), <anonymous>:3250:137)
    at _process_class3815 (eval at VFSLoader.exec_module (brython.min.js:91), <anonymous>:3259:34)
    at wrap3823 (eval at VFSLoader.exec_module (brython.min.js:91), <anonymous>:3760:79)
    at dataclass3822 (eval at VFSLoader.exec_module (brython.min.js:91), <anonymous>:3806:49)
    at eval (eval at run_py (brython.min.js:91), <anonymous>:42:46)
    at eval (eval at run_py (brython.min.js:91), <anonymous>:49:26)

brython.min.js:81 
(5) ['dataclasses__is_type_2170', {…}, 'dataclasses', {…}, ƒ]
0: "dataclasses__is_type_2170"
1: {annotation: 'int', cls: {…}, a_module: {…}, a_type: {…}, is_type_predicate: ƒ, …}
2: "dataclasses"
3: {__class__: {…}, __name__: 'dataclasses', __doc__: {…}, __package__: '', __initialized__: true, …}
4: ƒ _is_type3808(_annotation, _cls, _a_module, _a_type, _is_type_predicate)
length: 5
[[Prototype]]: Array(0)
```
### To reproduce

mymodule.py:
```
from dataclasses import dataclass


@dataclass
class MyDataclass:
    value: int
```

test.html:
```
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/brython/3.9.6/brython.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/brython/3.9.6/brython_stdlib.min.js"></script>
</head>
<body onload="brython(1)">
<script type="text/python">
import pickle
from mymodule import MyDataclass

data = MyDataclass(1)
pickled = pickle.dumps(data)
unpickled = pickle.loads(pickled)
print(unpickled.value)
</script>
</body>
```

The above code works if the script versions are changed to 3.9.5.

**Comment by alex-and-or** [comment]
Thanks!
