### PR TITLE
Fixes #2569: don't use time_ns

### LINKED ISSUE #2569: import logging fails
Thank you for this framework, it looks really fun to use!

But when I'm trying to `import logging`, I get the following error on 3.13.1:

```
Traceback (most recent call last):
  File "#__main__", line 1, in <module>
    import logging
  File "VFS.logging/__init__.py", line 59, in <module>
    _startTime=time.time_ns()
               ^^^^^^^^^^^^
AttributeError: 'module' object has no attribute 'time_ns'. Did you mean: 'timezone'?
```

It worked on 3.12.5.

### PR DESCRIPTION
**Pull request by YtvwlD**
Browsers don't seem to allow access to the nanoseconds. This basically just reverts [1316692](https://github.com/python/cpython/commit/1316692e8c7c1e1f3b6639e51804f9db5ed892ea).

I tried running the test suite but failed (I just got a `403: Forbidden`).

### CODE REVIEW

**Comment by YtvwlD** [comment]
Well, yes, but I don't think this can be implemented (at least with a quick look on [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Performance/now)):

 * `Date.now()` gives us the time since the epoch, but in milliseconds.
 * `Performance.now()` returns the time since page load in microseconds. This is more difficult to use (think: readjustments to the system time) and still not precise enough.

Besides, I don't think `logging` really needs nanosecond resolution.

**Comment by denis-migdal** [comment]
> * `Performance.now()` returns the time since page load in microseconds.

In ms, with a precision of ~5us in browsers.

In Node, there is `process.hrtime()` which has a precision in ns.

> and still not precise enough.

No, what matters is the unit. `time_ns` must be in `ns` (so we just have to multiply the time in ms by 1,000,000).

This doesn't mean that the precision must be in `ns`.
You'll always have some imprecision when measuring time. 

> Besides, I don't think `logging` really needs nanosecond resolution.

Maybe not ns indeed, but maybe us.

**Comment by PierreQuentel** [comment]
Thanks to both of you for the contribution. As I explained in the fix for issue #2569 I have implemented `time_ns()`, defaulting to `time() * 1000000`, but using the new Javascript [`Temporal`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Temporal) object when it is available (which is not the case at the moment on Firefox, Chrome or Edge)
