### ISSUE TITLE
dictionaries passed to `console.debug` are afterwards JavaScript objects and no longer Python dictionaries

### ISSUE THREAD

**Issue by grrchen** [brython-dev/brython#2681]
Good morning!

Since upgrading from version 3.13.1 to 3.14.1, dictionaries passed to the `console.debug` function are converted into JavaScript objects. So, when I try to access the dictionary after the `console.debug` call, it is no longer a Python dictionary. Instead it's a JavaScript object, which of course does not behave like a Python dict and leads in my code to an error like this:

```python
Traceback (most recent call last):
  File "home/grrchen/grrchen/brython/issues/4/issue_demo.html#__main__", line 30, in on_message
    msg_type = meta_data.get("message_type", None)
AttributeError: 'Javascript Object' object has no attribute 'get'
```

When I comment out `console.debug("websocket data:", data)`, my code works as expected.

# Issue Demo

Steps to reproduce:
 - start the sample web socket server: `python3 ws_server.py`
 - open the `issue_demo.html` file in your web browser

## ws_server.py
```python
import asyncio
from websockets.asyncio.server import serve


test_message = r'{"metadata":{"message_id":"1ee4b800-9493-4147-afb1-16b431266645","message_type":"session_welcome","message_timestamp":"2026-05-12T01:41:08.432041449Z"},"payload":{"session":{"id":"AgoQz5BDs_dbT0e7ugXK7lWLRBIGY2VsbC1h","status":"connected","connected_at":"2026-05-12T01:41:08.428433694Z","keepalive_timeout_seconds":10,"reconnect_url":null,"recovery_url":null}}}'


async def handle_messages(websocket):
    async for message in websocket:
        await websocket.send(test_message)


async def main():
    async with serve(handle_messages, "localhost", 8765) as server:
        await server.serve_forever()


if __name__ == "__main__":
    asyncio.run(main())
```

## issue_demo.html

```python
<!doctype html>
<html>
    <head>
        <meta charset="UTF-8">

        <script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython.js"
                crossorigin="anonymous">
        </script>
        <script src="https://raw.githack.com/brython-dev/brython/master/www/src/brython_stdlib.js"
                crossorigin="anonymous">
        </script>

        <title>Issue Demo</title>
    </head>
    <body>
        <script type="text/python">
from browser import console, websocket
import json


class Overlay:

    _ws_url: str = "ws://localhost:8765"

    def __init__(self):
        self.connect()

    def connect(self):
        # open a web socket
        self._ws = ws = websocket.WebSocket(self._ws_url)
        # bind functions to web socket events
        ws.bind('open', self.on_open)
        ws.bind('message', self.on_message)

    def on_open(self, evt):
        self._ws.send("test data")

    def on_message(self, evt):
        console.debug("evt data:", evt.data)
        data = json.loads(evt.data)
        # vvvv - If this line is commented out, no error occurs
        console.debug("websocket data:", data)
        # ^^^^
        meta_data: dict = data.get("metadata", {})
        payload: dict = data.get("payload", {})
        msg_type = meta_data.get("message_type", None)


overlay = Overlay()
        </script>
    </body>
</html>
```

Thanks in advance!

**Comment by PierreQuentel** [comment]
Many thanks for the detailed report !
