### ISSUE TITLE
Install 3.9.0 from pip fails

### ISSUE THREAD

**Issue by polm** [brython-dev/brython#1556]
Hello, trying to use brython for the first time and getting this error installing from pip:

    AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'

Full error output:

<details markdown=1>
<pre><code>
    ERROR: Command errored out with exit status 1:
     command: /mnt/pool/fiddle/nessie/env/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-n687vdgl/brython_bccc7e401d1a417e9cef91fc11030656/setup.py'"'"'; __file__='"'"'/tmp/pip-install-n687vdgl/brython_bccc7e401d1a417e9cef91fc11030656/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-pb3aow1r
         cwd: /tmp/pip-install-n687vdgl/brython_bccc7e401d1a417e9cef91fc11030656/
    Complete output (16 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/mnt/pool/fiddle/nessie/env/lib/python3.9/site-packages/setuptools/__init__.py", line 12, in <module>
        from setuptools.extension import Extension
      File "/mnt/pool/fiddle/nessie/env/lib/python3.9/site-packages/setuptools/extension.py", line 7, in <module>
        from setuptools.dist import _get_unpatched
      File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
      File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
      File "/mnt/pool/fiddle/nessie/env/lib/python3.9/site-packages/_virtualenv.py", line 89, in exec_module
        old(module)
      File "/mnt/pool/fiddle/nessie/env/lib/python3.9/site-packages/setuptools/dist.py", line 16, in <module>
        import pkg_resources
      File "/mnt/pool/fiddle/nessie/env/lib/python3.9/site-packages/pkg_resources.py", line 1479, in <module>
        register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
    AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
</pre></code>
</details>

Python versions is 3.9.0, pip version is 20.3.1, and I'm on Linux. I am using a virtualenv. Let me know if there's any other information I can provide.

I saw  that 3.9.0 is supposed to work with py 3.9, so not sure what would be causing this.

**Comment by PierreQuentel** [comment]
@polm I can't reproduce the issue. A search with this error message suggests [this answer](https://stackoverflow.com/questions/44761958/using-pip3-module-importlib-bootstrap-has-no-attribute-sourcefileloader) on stackoverflow. Does it solve the issue ?

**Comment by polm** [comment]
Looking over things in that question, uninstalling and then re-installing setuptools fixed it for me. 

I'm confused as to why this happened, since the venv is new today and I had just upgraded setuptools for an issue with a separate package ([see here](https://stackoverflow.com/questions/65040971/why-is-pip3-install-netifaces-failing-on-debian-10-buster)). But recreating a blank venv I can't reproduce the issue.

Sorry for the false alarm.
