### ISSUE TITLE
Ajax module bug

### ISSUE THREAD

**Issue by fsvend** [brython-dev/brython#367]
This does not work in Safari v9.0.3
```
from browser import ajax
req = ajax.ajax()
```
It fails with
```
Internal Javascript error: TypeError: undefined is not an object (evaluating 'self.func.bind')
```
Here's some info on why it happens:
```
>>> from javascript import JSConstructor
>>> from browser import window
>>> req = JSConstructor(window.XMLHttpRequest)
>>> req()

Internal Javascript error: TypeError: undefined is not an object (evaluating 'self.func.bind')
>>> dir(req)
['__bases__', '__call__', '__class__', '__delattr__', '__dir__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__name__', '__ne__', '__new__', '__or__', '__repr__', '__setattr__', '__str__', '__subclasshook__', 'func']
>>> type(req.func)
Traceback (most recent call last):
AttributeError: 'JSConstructor' object has no attribute 'func'
>>> 
```
Note that dir(req) is listing 'func', and still we get the no attribute error. FYI, this works fine in Firefox, Chrome, IE 11 and MS "Edge".

**Comment by auduntorp** [comment]
I get the same error message when using PhantomJS to selenium-test my brython page.

Console log from PhantomJS:
```
[2016-01-26T13:33:15+0100] [INFO] Javascript error TypeError: undefined is not an object (evaluating 'self.func.bind') (:)
[2016-01-26T13:33:15+0100] [INFO] Traceback (most recent call last):
RuntimeError: TypeError: undefined is not an object (evaluating 'self.func.bind') (:)
[2016-01-26T13:33:15+0100] [WARNING] Error
  run_script (https://cdn.rawgit.com/brython-dev/brython/3.2.4/www/src/brython_dist.js:4078)
  brython (https://cdn.rawgit.com/brython-dev/brython/3.2.4/www/src/brython_dist.js:4154)
  onload (http://localhost:6080/:14)
```

**Comment by PierreQuentel** [comment]
This should be fixed in commit e57612a9313a2faf2235a0a7823f4d5f22e5e27f : if it's the case can we close the issue ?

**Comment by fsvend** [comment]
It is fixed yes, so I'll close it.
