### ISSUE TITLE
`str` subclasses are not working properly.

### ISSUE THREAD

**Issue by goffi-contrib** [brython-dev/brython#2747]
Hello,

With Brython 3.14.1, a `str` subclass is not working properly, calling `find` on it fails.

This has been tested with Brython editor from official website.

**Steps to reproduce:**

Run this code:
```python
class SubStr(str):
    pass

toto = SubStr("toto")
print(toto)
print(toto.find("o"))
```

**Expected result:**
```
toto
1
```

**Actual result:**
```
toto
Traceback (most recent call last):
  File <string>, line 6, in <module>
    print(toto.find("o"))
JavascriptError: self.indexOf is not a function
```

A workaround is to clone the class like that:
```python
class SubStr(str):
    pass

toto = SubStr("toto")
print(toto)
tata = str(toto)
print(tata.find("o"))
```

This was working correctly with Brython 3.13.2 .

Thanks!

**Comment by PierreQuentel** [comment]
Thanks Jérôme, much appreciated as usual :-)

**Comment by tavanh2025123-netizen** [comment]
#2747
