### ISSUE TITLE
import logging fails

### ISSUE THREAD

**Issue by YtvwlD** [brython-dev/brython#2569]
Thank you for this framework, it looks really fun to use!

But when I'm trying to `import logging`, I get the following error on 3.13.1:

```
Traceback (most recent call last):
  File "#__main__", line 1, in <module>
    import logging
  File "VFS.logging/__init__.py", line 59, in <module>
    _startTime=time.time_ns()
               ^^^^^^^^^^^^
AttributeError: 'module' object has no attribute 'time_ns'. Did you mean: 'timezone'?
```

It worked on 3.12.5.

**Comment by PierreQuentel** [comment]
Thanks for the report Niklas. I have added the function `time_ns()`. Javascript defines a new object `Temporal` that is not widely supported at the moment but will provide time with nanosecond precision. `time_ns()` uses it when available and defauts to `time() * 1000000` otherwise.
