### ISSUE TITLE
How to create a Component

### ISSUE THREAD

**Issue by jgcb00** [brython-dev/brython#2231]
Hi,
I'm trying to create some abstraction base on the `browser.html` package, but I just don't get how to do this, here is my try, what am I doing wrong ? 

```
from browser.html import DIV, SPAN, I
from browser import document

"""
    <div class="info-box">
  <span class="info-box-icon bg-info"><i class="far fa-envelope"></i></span>
  <div class="info-box-content">
    <span class="info-box-text">Messages</span>
    <span class="info-box-number">1,410</span>
  </div>
</div>
"""

class Box():
    
    def __init__(self, icon, text, number):
        self.icon = icon
        self.text = text
        self.number = number

    def __le__(self, others):
        return others <= DIV(
            SPAN(
                I(Class=self.icon),
            ) + 
            DIV(
                SPAN(self.text, Class="info-box-text")
                    +
                SPAN(self.number, Class="info-box-number")
            ),
            Class="info-box"                
        )
        
document <= Box("far fa-envelope", "Messages", "1,410")      
```

**Comment by jgcb00** [comment]
It works, if I change it to a function : 
```
def Box(icon, text, number):
    return DIV(
            SPAN(
                I(Class=icon),
            ) + 
            DIV(
                SPAN(text, Class="info-box-text")
                    +
                SPAN(number, Class="info-box-number")
            ),
            Class="info-box"          
        )
```

But I would like to work with class, it's proper to indroduce callbacks and stuff like that

**Comment by PierreQuentel** [comment]
Hi,

In `document <= element`, `element` must be a DOM element, typically created by a class in the **`html`** module, for instance

```python
document <= html.DIV('hello')
```

In your example, class `Box` does not produce DOM elements. To achieve this, it should inherit one of the classes in **`html`**. Here is a working example:

```python
from browser.html import DIV, SPAN, I
from browser import document

class Box(DIV):

    def __init__(self, icon, text, number):
        super().__init__(Class='info-box') # create a DIV
        self <= (SPAN(I(Class=icon)) +
                 DIV(
                   SPAN(text, Class="info-box-text") +
                   SPAN(number, Class="info-box-number")
                 )
                )

document <= Box("far fa-envelope", "Messages", "1,410")
```

**Comment by jgcb00** [comment]
Thanks, I have another issue, I see in the documentation that enum is a specific library, how can I import it ?

**Comment by PierreQuentel** [comment]
> Thanks, I have another issue, I see in the documentation that enum is a specific library, how can I import it ?

Did you try `import enum` ?

The documentation says that the module is not the same in Brython 3.11 and CPython 3.11 but even in this case, imports should work.

**Comment by jgcb00** [comment]
I run into this issue : 
```
File "http://localhost:8000/Box.py", line 2, in <module>
    from enum import Enum
  File "VFS.enum.py", line 1, in <module>
    import sys
  File "VFS.sys.py", line 112, in <module>
    stdlib_module_names=frozenset(__BRYTHON__.stdlib_module_names)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Javascript Object' object has no attribute 'stdlib_module_names'. Did you mean: 'builtin_module_names'?
```

**Comment by PierreQuentel** [comment]
Very strange... which version of **`brython.js`** and **`brython_stdlib.js`** do you use ?

**Comment by jgcb00** [comment]
I follow the documentation to install everything : 
`brython-cli install` 
`brython-cli --version` returns `Brython version 3.11.1`

**Comment by PierreQuentel** [comment]
Thanks, I could reproduce the bug with version 3.11.1, but it has been fixed in version 3.11.3.

**Comment by jgcb00** [comment]
Okay thanks,
but when I tried to update it , it fails, is it only compatible with python3.11 ?
```
pip install brython --upgrade

Requirement already satisfied: brython in ./brython_env/lib/python3.10/site-packages (3.11.1)
```

**Comment by PierreQuentel** [comment]
I get the same message when upgrading from 3.11.1, but the new version is installed.

```
D:\brython\20221025>pip install brython --upgrade
Requirement already satisfied: brython in c:\python312\lib\site-packages (3.11.1)
Collecting brython
  Using cached brython-3.11.3-py3-none-any.whl (1.6 MB)
Installing collected packages: brython
  Attempting uninstall: brython
    Found existing installation: brython 3.11.1
    Uninstalling brython-3.11.1:
      Successfully uninstalled brython-3.11.1
Successfully installed brython-3.11.3

[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

D:\brython\20221025>brython-cli --version
Brython version 3.11.3
```

It is doesn't work for you, you can try `pip uninstall brython` then `pip install brython`
