### ISSUE TITLE
AttributeError: 'module' object has no attribute 'util'

### ISSUE THREAD

**Issue by moepnse** [brython-dev/brython#2195]
Hello,

the following code works with Python 3.11, but not with the latest Brython snapshot.

```python
Python 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import importlib
>>> module_spec = importlib.util.find_spec('sys')
>>> module = importlib.util.module_from_spec(module_spec)
>>> module_spec.loader.exec_module(module)
>>> module
<module 'sys' (built-in)>
```

The same code with Brython:
```python
Traceback (most recent call last):
  File "file:///C:/Users/user1/issues/brython_issue_20230525.html#__main__", line 2, in <module>
    module_spec = importlib.util.find_spec('sys')
                  ^^^^^^^^^^^^^^
AttributeError: 'module' object has no attribute 'util'
```

Adapted code for Brython:
```python
import importlib
import importlib.util
module_spec = importlib.util.find_spec('sys')
module = importlib.util.module_from_spec(module_spec)
module_spec.loader.exec_module(module)
```

```python
Traceback (most recent call last):
  File "file:///C:/Users/user1/issues/brython_issue_20230525.html#__main__", line 3, in <module>
    module_spec = importlib.util.find_spec('sys')
                                 ^^^^^^^^^^^^^^^^
  File "VFS.importlib.util.py", line 111, in find_spec
    raise ValueError('{}.__spec__ is not set'.format(name))from None
ValueError: sys.__spec__ is not set
```

Thanks for your time!

**Comment by PierreQuentel** [comment]
Sorry for the very late answer, I must have tested the example without **`brython_stdlib.js`** included in the page, and the bug only happens when it is included.

The commit referenced above seems to fix the issue. Can you check ?

**Comment by PierreQuentel** [comment]
I tested again with CPython 3.11.1 and I get the same error message as on Brython
```python
Python 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import importlib
>>> module_spec = importlib.util.find_spec('sys')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'importlib' has no attribute 'util'
```

It's the same with the latest pre-release of CPython 3.12
```python
Python 3.12.0b2 (tags/v3.12.0b2:e6c0efa, Jun  6 2023, 15:37:48) [MSC v.1935 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import importlib
>>> module_spec = importlib.util.find_spec('sys')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'importlib' has no attribute 'util'
>>>
```

It seems that you have to explicitely `import importlib.util`
